### PR TITLE
Translate home

### PR DESCRIPTION
**Pull request by Zitle-Nancy**

### CODE REVIEW

**Comment by tesseralis** [comment]
@Zitle-Nancy you need to keep the english headings on IDs:

e.g.

```
## Eventos Soportados {#supported-events}
```

**Comment by tesseralis** [comment]
@carburo why did you delete `reference-events`? Did you mean to just unstage the changes?

**Comment by carburo** [comment]
Yeah, @tesseralis I meant to fix it right away, but then I had troubles with my internet connection.

**Comment by Zitle-Nancy** [comment]
Hi!, Thanks for helping me.
I want to know if I can help in any other part of the project, I think it could be in the translate of navbar and footer, If you need my help with these, just tell me.

Cheerse!

**Comment by carburo** [comment]
Yes, @Zitle-Nancy, all help is needed. I'll assign you in #4.

**Comment by Zitle-Nancy** [comment]
Cool @carburo , I'll do it!

**Pull request closed without merging**
