### PR TITLE
Update missing translation in code comment. JSX in depth

### PR DESCRIPTION
**Pull request by alejandronanez**
Updating `return` to `retorna`

### CODE REVIEW

**Comment by tesseralis** [comment]
I think in this case the comment means "this was what the code previously was, but we're changing it" -- it's supposed to represent code so should just stay `return`.

**Comment by alejandronanez** [comment]
Hey @tesseralis, yep, I get the point, but we're translating other `return` occurrences as well. I made the change to keep things consistent! 😄

**Comment by carburo** [comment]
Yep, you're right

**Comment by carburo** [comment]
I see @tesseralis point. Maybe we should changes the other way around?

**Comment by alejandronanez** [comment]
Well, we already have translated other `return` and `returns` into `retorna` - I think we should stick to `retorna` to be consistent.

**Comment by carburo** [comment]
Yes, it's fine. Maybe I just didn't make myself clear. Usually, we translate "return" and "returns" but in this case, although the text is in comments it's actually code.

**Pull request merged**
