### PR TITLE
Changing lifting up translation from "Levantando" to "Elevando"

### PR DESCRIPTION
**Pull request by tonig**

### CODE REVIEW

**Comment by carburo** [comment]
>  Changing lifting up translation from "Levantando" to more accurate "Elevando"
@tonig Why is it more accurate? I think they can be used here as synonyms without loosing any meaning.

**Comment by tonig** [comment]
The meaning for "Levantar" is "to raise", "levantar las manos", "raise
hands", and also related to something that was down. But sounds odd for
transporting something between levels. For example, you can say "El
ascensor eleva a las personas a las plantas superiores" but  "El ascensor
levanta a las personas a las plantas superiores" does not sound well.

**Comment by carburo** [comment]
Yes, I see your point. Still, I don't think the analogy applies 100%, and "it doesn't sound well" is rather subjective and is not necessarily a reason to change terms that are already established throughout the docs. I will leave this open to see if the other maintainers have a different opinion about this.

**Comment by Darking360** [comment]
Greetings @tonig I'd say it's a good point, but as @carburo mentions, the problem is that we've already established most of the docs with that wording, if we're going to change it we'd need to find all the old wording and change it :thinking: I'd say it's a little risky since we have tons of the documentation already translated :sweat_smile: 

CC: @alejandronanez @carburo

**Comment by alejandronanez** [comment]
Yep, I agree with y'all - let's stick to the original wording.

I'm closing this for now.

**Pull request closed without merging**
